# Generated by Django 5.1.7 on 2025-04-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('webside', models.URLField(max_length=100)),
            ],
        ),
    ]
