# Generated by Django 5.1.7 on 2025-04-08 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_showroommodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showrooms', to='cars.showroommodel'),
        ),
    ]
