# Generated by Django 5.1.7 on 2025-04-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_reviewmodel_created_at_reviewmodel_userapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='userapi',
        ),
    ]
